routes/web.php
<?php


Route::namespace('Admin')->prefix('admin')->group(function () {
    Route::get('home', 'HomeController@index')->name('admin.home.index');

	Route::resource('forum', 'ForumController', ['as' => 'admin'])->except(['show']);
    Route::resource('/forum/category', 'ForumCategoryController', ['as' => 'admin.forum'])->except(['show']);

    Route::get('/forum/{forum}/subforum/create', 'SubForumController@create')->name('admin.forum.subforum.create');
    Route::post('/forum/{forum}/subforum', 'SubForumController@store')->name('admin.forum.subforum.store');
    Route::get('/forum/subforum/{subforum}', 'SubForumController@show')->name('admin.forum.subforum.show');
    Route::delete('/forum/subforum/{subforum}', 'SubForumController@destroy')->name('admin.forum.subforum.destroy');
});

Route::namespace('App')->prefix('home')->group(function () {
    Route::get('', 'HomeController@index')->name('app.home.index');

    Route::get('/forum', 'ForumController@index')->name('app.forum.index');
    Route::get('/forum/{forum}', 'ForumController@show')->name('app.forum.show');
    
    Route::get('/forum/{forum}/thread/create', 'ForumThreadController@create')->name('app.forum.thread.create');
    Route::get('/thread/{thread}', 'ForumThreadController@show')->name('app.forum.thread.show');
    Route::post('/forum/{forum}/thread', 'ForumThreadController@store')->name('app.forum.thread.store');
    Route::delete('/thread/{thread}', 'ForumThreadController@destroy')->name('app.forum.thread.destroy');
    Route::post('/thread/{thread}/post', 'ForumPostController@store')->name('app.forum.post.store');

    Route::patch('/post/{post}', 'ForumPostController@update')->name('app.forum.post.update');
    Route::delete('/post/{post}', 'ForumPostController@destroy')->name('app.forum.post.destroy');
    Route::get('/post/{post}/edit', 'ForumPostController@edit')->name('app.forum.post.edit');

    Route::resource('/move/thread', 'ForumMoveThreadController', ['as' => 'app.forum.move'])->only(['edit', 'update']);
	Auth::routes();
});

app/Forum.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Forum extends Model
{
    protected $fillable = [
    	'name', 'description', 'position', 'category_id',
    ];

    /**
     * A forum belongs to a category.
     *
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function category()
    {
    	return $this->belongsTo(ForumCategory::class, 'category_id', 'id');
    }

    /**
     * A forum can have many threads.
     *
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function threads()
    {
        return $this->hasMany(ForumThread::class, 'forum_id', 'id')->with('user');
    }

    /**
     * A forum can have many subforums.
     *
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function subForums()
    {
        return $this->hasMany(SubForum::class, 'parent_id', 'id');
    }

    /**
     * Get all forums that is not a subforum.
     *
     * @return \Illuminate\Database\Query\Builder|static
     */
    public function nonSubForums()
    {
        return static::whereNotIn('id', $this->subforums->pluck('child_id'))->get();
    }

    /**
     * A forum has one latest post.
     *
     * @return \Illuminate\Database\Eloquent\Relations\HasOne
     */
    public function latestPost()
    {
        return $this->hasOne(LatestForumThread::class, 'forum_id', 'id');
    }
}

app/Http/Controllers/Admin/ForumController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Validation\Rule;
use App\Forum;
use App\ForumCategory;

class ForumController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('role:administrator');
    }

    /**
      * Display a listing of the resource.
      *
      * @return \Illuminate\Http\Response
      */
    public function index()
    {
		$categories = ForumCategory::orderby('position', 'asc')->get();
        return view('admin.forums.index', compact('categories'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
    	$categories = ForumCategory::get();
        return view('admin.forums.create', compact('categories'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        request()->validate([
            'name' => 'required',
            'description' => 'required',
            'category_id' => 'required',
            'position' => ['required', 'integer', 'between:1,100', Rule::unique('forums')->where(function ($query) use ($request) {
                    return $query->where('position', $request->position)->where('category_id', $request->category_id);
                }),
            ],
        ]);
    
        Forum::create(request()->all());
    
        return redirect()->route('admin.forum.index')->withSuccess('Forum Created.');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  Forum $forum
     * @return \Illuminate\Http\Response
     */
    public function edit(Forum $forum)
    {
        $categories = ForumCategory::get();
        return view('admin.forums.edit', compact('forum', 'categories'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param Request $request
     * @param  Forum $forum 
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Forum $forum)
    {
        request()->validate([
            'name' => 'required',
            'description' => 'required',
            'position' => ['required', 'integer', 'between:1,100', Rule::unique('forums')->where(function ($query) use ($request, $forum) {
                    return $query->where('position', '!=', $forum->position)->where('category_id', $request->category_id);
                }),
            ],
        ]);
    
        $forum->update(request()->all());
    
        return redirect()->route('admin.forum.index')->withSuccess('Forum Updated.');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  Forum $forum 
     * @return \Illuminate\Http\Response
     */
    public function destroy(Forum $forum)
    {
        $forum->delete();
        return redirect()->route('admin.forum.index')->withSuccess('Forum Deleted.');
    }
}

app/Http/Controllers/App/ForumController.php
<?php
namespace App\Http\Controllers\App;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Forum;
use App\ForumCategory;

class ForumController extends Controller
{
	/**
	  * Display a listing of the resource.
	  *
	  * @return \Illuminate\Http\Response
	  */
	public function index()
	{
		$categories = ForumCategory::orderby('position', 'asc')->get();
		return view('app.forums.index', compact('categories'));
	}

	/**
	 * Display the specified resource.
	 *
	 * @param  Forum $forum 
	 * @return \Illuminate\Http\Response
	 */
	public function show(Forum $forum)
	{
		$threads = $forum->threads()->orderBy('updated_at', 'desc')->paginate(10);
		return view('app.forums.show', compact('forum', 'threads'));
	}  
}

resources/views/admin/forums/create.blade.php
@extends('app.templates.default')

@section('navigation')
    @include('admin.templates.partials.navigation')
@endsection

@section('content')
	<h2>Create Forum</h2>
	@include('admin.templates.partials.messages.errors')

	<form action="{{ route('admin.forum.store') }}" method="POST">
		{{ csrf_field() }}
		<fieldset>
			<legend>Name</legend>
			<input type="text" name="name" value="{{ old('name') ? old('name') : '' }}">
		</fieldset>
		<fieldset>
			<legend>Description</legend>
			<input type="text" name="description" value="{{ old('description') ? old('description') : '' }}">
		</fieldset>
		<fieldset>
			<legend>Position</legend>
			<input type="text" name="position" value="{{ old('position') ? old('position') : '' }}">
		</fieldset>
		<fieldset>
			<legend>Category</legend>
			@if(!$categories->isEmpty())
				<select name="category_id" id="category_id">
					@foreach($categories as $category)
						<option value="{{ $category->id }}" @if(old('category_id') == $category->id) selected @endif>{{ $category->name }}</option>
					@endforeach
				</select>
			@else
				<a href="{{ route('admin.forum.category.create') }}">Create Category</a>
			@endif
		</fieldset>
		<button type="submit">Submit</button>
	</form>
@endsection

resources/views/admin/forums/edit.blade.php
@extends('app.templates.default')

@section('navigation')
    @include('admin.templates.partials.navigation')
@endsection

@section('content')
	<h2>Edit Forum</h2>
	@include('admin.templates.partials.messages.errors')

	<form action="{{ route('admin.forum.update', $forum) }}" method="POST">
		{{ csrf_field() }}
		{{ method_field('PATCH') }}
		<fieldset>
			<legend>Name</legend>
			<input type="text" name="name" value="{{ $forum->name }}">
		</fieldset>
		<fieldset>
			<legend>Description</legend>
			<input type="text" name="description" value="{{ $forum->description }}">
		</fieldset>
		<fieldset>
			<legend>Position</legend>
			<input type="text" name="position" value="{{ $forum->position }}">
		</fieldset>
		<fieldset>
			<legend>Category</legend>
			@if(!$categories->isEmpty())
				<select name="category_id" id="category_id">
					@foreach($categories as $category)
						<option value="{{ $category->id }}" @if($forum->category->id == $category->id) selected @endif>{{ $category->name }}</option>
					@endforeach
				</select>
			@endif
		</fieldset>
		<button type="submit">Submit</button>
	</form>
@endsection

resources/views/admin/forums/index.blade.php
@extends('app.templates.default')

@section('navigation')
    @include('admin.templates.partials.navigation')
@endsection

@section('content')
	<p>
		@include('admin.templates.partials.messages.success')
	</p>
	<h2>Categories</h2>
	<p>
		<a href="{{ route('admin.forum.category.create') }}">Create Category</a>
	</p>
	@if(!$categories->isEmpty())
		<fieldset>
			@foreach ($categories as $category) 
				{{ $category->name }} - <a href="{{ route('admin.forum.category.edit', $category) }}">edit</a>
				<form action="{{ route('admin.forum.category.destroy', $category) }}" method="POST">
					{{ csrf_field() }}
					{{ method_field('DELETE') }}
					<button type="submit">delete</button>
				</form>
				<hr>
			@endforeach
		</fieldset>
	@endif

	<h2>Forums</h2>
	<p>
		<a href="{{ route('admin.forum.create') }}">Create Forum</a>
	</p>
	@foreach ($categories as $category) 
		<fieldset>
			<legend>{{ $category->name }}</legend>
			@foreach ($category->forums as $forum) 
				{{ $forum->name }} - <a href="{{ route('admin.forum.edit', $forum) }}">edit</a>
					<form action="{{ route('admin.forum.destroy', $forum) }}" method="POST">
						{{ csrf_field() }}
						{{ method_field('DELETE') }}
						<button type="submit">delete</button>
						@if(!$forum->subforums->isEmpty())
							<p>
								<strong>Subforums</strong>
							</p>
							@foreach($forum->subforums as $subforum)
								<fieldset>
									<a href="{{ route('admin.forum.subforum.show', $subforum) }}">{{ $subforum->forum->name }}</a> 
								</fieldset>
							@endforeach
						@endif
					</form>

					<a href="{{ route('admin.forum.subforum.create', $forum) }}">Add subforum</a>
				<hr>
			@endforeach
		</fieldset>
	@endforeach
@endsection